sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python
python:
  - "2.7"

env:
  - VERSION="9.0" ODOO_REPO="odoo/odoo"
  - VERSION="9.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - pip install simple-salesforce
  - pip install requests
  - git clone https://github.com/OCA/server-tools ${HOME}/server-tools -b ${VERSION}
  - git clone https://github.com/OCA/connector ${HOME}/connector -b ${VERSION}
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - ln -s ${HOME}/server-tools/server_environment_files_sample ${HOME}/server-tools/server_environment_files
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_flake8
  - travis_run_tests ${VERSION}

after_success:
  coveralls